"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18 14:56:28.990071
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "academic_terms",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("section_timetable", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_academic_terms_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_terms")),
        sa.UniqueConstraint("department_id", "code", name="uq_academic_terms_department_code"),
    )
    op.create_index(
        op.f("ix_academic_terms_department_id"), "academic_terms", ["department_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("before_summary", sa.JSON(), nullable=True),
        sa.Column("after_summary", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_object_id"), "audit_logs", ["object_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_object_type"), "audit_logs", ["object_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "directions",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_directions_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directions")),
        sa.UniqueConstraint("department_id", "code", name="uq_directions_department_code"),
    )
    op.create_index(
        op.f("ix_directions_department_id"), "directions", ["department_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("template_kind", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "ready",
                "confirmed",
                "failed",
                name="import_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=1000), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("uploader_id", sa.Uuid(), nullable=False),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("create_count", sa.Integer(), nullable=False),
        sa.Column("update_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_by_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_id"],
            ["users.id"],
            name=op.f("fk_import_batches_confirmed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_import_batches_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
            name=op.f("fk_import_batches_uploader_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_department_id"), "import_batches", ["department_id"], unique=False
    )
    op.create_table(
        "leave_records",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column(
            "person_type",
            sa.Enum("student", "teacher", name="person_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "rejected", "revoked", name="leave_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_leave_records_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_records")),
        sa.UniqueConstraint(
            "department_id", "source_fingerprint", name="uq_leave_records_department_fingerprint"
        ),
    )
    op.create_index(
        op.f("ix_leave_records_department_id"), "leave_records", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_records_person_id"), "leave_records", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_records_starts_at"), "leave_records", ["starts_at"], unique=False
    )
    op.create_table(
        "majors",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_majors_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_majors")),
        sa.UniqueConstraint("department_id", "code", name="uq_majors_department_code"),
    )
    op.create_index(op.f("ix_majors_department_id"), "majors", ["department_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("device_info", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_refresh_tokens_token_digest")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "role_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("system_admin", "academic_admin", "teacher", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("can_approve_exceptions", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_role_assignments_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint(
            "user_id", "role", "department_id", name="uq_role_assignments_user_role_department"
        ),
    )
    op.create_index(
        op.f("ix_role_assignments_department_id"),
        "role_assignments",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_assignments_user_id"), "role_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("campus", sa.String(length=120), nullable=False),
        sa.Column("building", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_rooms_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("campus", "building", "name", name="uq_rooms_campus_building_name"),
    )
    op.create_index(op.f("ix_rooms_department_id"), "rooms", ["department_id"], unique=False)
    op.create_table(
        "teachers",
        sa.Column("employee_number", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("title_rank", sa.Integer(), nullable=False),
        sa.Column("workload_limit", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_teachers_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_teachers_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teachers")),
        sa.UniqueConstraint("user_id", name=op.f("uq_teachers_user_id")),
    )
    op.create_index(op.f("ix_teachers_department_id"), "teachers", ["department_id"], unique=False)
    op.create_index(
        op.f("ix_teachers_employee_number"), "teachers", ["employee_number"], unique=True
    )
    op.create_table(
        "course_occupancies",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column(
            "person_type",
            sa.Enum("student", "teacher", name="person_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("academic_term_id", sa.Uuid(), nullable=True),
        sa.Column("teaching_week", sa.Integer(), nullable=True),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("start_section", sa.Integer(), nullable=True),
        sa.Column("end_section", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_term_id"],
            ["academic_terms.id"],
            name=op.f("fk_course_occupancies_academic_term_id_academic_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_course_occupancies_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_occupancies")),
        sa.UniqueConstraint(
            "department_id",
            "source_fingerprint",
            name="uq_course_occupancies_department_fingerprint",
        ),
    )
    op.create_index(
        op.f("ix_course_occupancies_department_id"),
        "course_occupancies",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_occupancies_person_id"), "course_occupancies", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_occupancies_starts_at"), "course_occupancies", ["starts_at"], unique=False
    )
    op.create_table(
        "defense_activities",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("academic_term_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("academic_year", sa.String(length=20), nullable=False),
        sa.Column("semester", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("configuring", "ready", "closed", name="activity_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("current_rule_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_term_id"],
            ["academic_terms.id"],
            name=op.f("fk_defense_activities_academic_term_id_academic_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_defense_activities_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defense_activities")),
    )
    op.create_index(
        op.f("ix_defense_activities_department_id"),
        "defense_activities",
        ["department_id"],
        unique=False,
    )
    op.create_table(
        "room_availabilities",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("available_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_availabilities_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_availabilities")),
        sa.UniqueConstraint(
            "room_id",
            "available_date",
            "start_time",
            "end_time",
            name="uq_room_availabilities_interval",
        ),
    )
    op.create_index(
        op.f("ix_room_availabilities_room_id"), "room_availabilities", ["room_id"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("student_number", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("major_id", sa.Uuid(), nullable=False),
        sa.Column("advisor_id", sa.Uuid(), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisor_id"],
            ["teachers.id"],
            name=op.f("fk_students_advisor_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_students_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["major_id"],
            ["majors.id"],
            name=op.f("fk_students_major_id_majors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(op.f("ix_students_advisor_id"), "students", ["advisor_id"], unique=False)
    op.create_index(op.f("ix_students_department_id"), "students", ["department_id"], unique=False)
    op.create_index(op.f("ix_students_major_id"), "students", ["major_id"], unique=False)
    op.create_index(op.f("ix_students_student_number"), "students", ["student_number"], unique=True)
    op.create_table(
        "teacher_directions",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["directions.id"],
            name=op.f("fk_teacher_directions_direction_id_directions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_directions_teacher_id_teachers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("teacher_id", "direction_id", name=op.f("pk_teacher_directions")),
    )
    op.create_table(
        "activity_rooms",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_activity_rooms_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_activity_rooms_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("activity_id", "room_id", name=op.f("pk_activity_rooms")),
    )
    op.create_table(
        "activity_rule_sets",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("students_per_group", sa.Integer(), nullable=False),
        sa.Column("teachers_per_group", sa.Integer(), nullable=False),
        sa.Column("chair_min_title_rank", sa.Integer(), nullable=False),
        sa.Column("teacher_workload_limit", sa.Integer(), nullable=False),
        sa.Column("soft_weights", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_activity_rule_sets_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_rule_sets")),
        sa.UniqueConstraint("activity_id", "rule_version", name="uq_activity_rule_sets_version"),
    )
    op.create_index(
        op.f("ix_activity_rule_sets_activity_id"),
        "activity_rule_sets",
        ["activity_id"],
        unique=False,
    )
    op.create_table(
        "defense_slots",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("max_groups", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_defense_slots_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defense_slots")),
        sa.UniqueConstraint(
            "activity_id",
            "slot_date",
            "start_time",
            "end_time",
            name="uq_defense_slots_activity_interval",
        ),
    )
    op.create_index(
        op.f("ix_defense_slots_activity_id"), "defense_slots", ["activity_id"], unique=False
    )
    op.create_table(
        "schedule_jobs",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("input_summary", sa.JSON(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("result_plan_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_schedule_jobs_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_schedule_jobs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_plan_id"],
            ["schedule_plans.id"],
            name=op.f("fk_schedule_jobs_result_plan_id_schedule_plans"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_jobs")),
        sa.UniqueConstraint(
            "created_by_id", "idempotency_key", name="uq_schedule_jobs_creator_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_schedule_jobs_activity_id"), "schedule_jobs", ["activity_id"], unique=False
    )
    op.create_table(
        "schedule_plans",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_plan_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "validating",
                "ready",
                "published",
                "archived",
                name="plan_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("solver_parameters", sa.JSON(), nullable=False),
        sa.Column("quality_metrics", sa.JSON(), nullable=False),
        sa.Column("exception_snapshot", sa.JSON(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_schedule_plans_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_schedule_plans_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_plan_id"],
            ["schedule_plans.id"],
            name=op.f("fk_schedule_plans_source_plan_id_schedule_plans"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_plans")),
        sa.UniqueConstraint("activity_id", "version_number", name="uq_schedule_plans_version"),
    )
    op.create_index(
        op.f("ix_schedule_plans_activity_id"), "schedule_plans", ["activity_id"], unique=False
    )
    op.create_table(
        "student_directions",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["directions.id"],
            name=op.f("fk_student_directions_direction_id_directions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_directions_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("student_id", "direction_id", name=op.f("pk_student_directions")),
    )
    op.create_table(
        "constraint_exceptions",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("constraint_code", sa.String(length=80), nullable=False),
        sa.Column("subject_type", sa.String(length=40), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("student_id", sa.Uuid(), nullable=True),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("slot_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("approver_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "revoked",
                name="approval_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["defense_activities.id"],
            name=op.f("fk_constraint_exceptions_activity_id_defense_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
            name=op.f("fk_constraint_exceptions_approver_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_constraint_exceptions_requester_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["defense_slots.id"],
            name=op.f("fk_constraint_exceptions_slot_id_defense_slots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_constraint_exceptions_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_constraint_exceptions_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constraint_exceptions")),
    )
    op.create_index(
        op.f("ix_constraint_exceptions_activity_id"),
        "constraint_exceptions",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constraint_exceptions_constraint_code"),
        "constraint_exceptions",
        ["constraint_code"],
        unique=False,
    )
    op.create_table(
        "defense_groups",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["schedule_plans.id"],
            name=op.f("fk_defense_groups_plan_id_schedule_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_defense_groups_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["defense_slots.id"],
            name=op.f("fk_defense_groups_slot_id_defense_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defense_groups")),
        sa.UniqueConstraint("plan_id", "code", name="uq_defense_groups_plan_code"),
        sa.UniqueConstraint(
            "plan_id", "slot_id", "room_id", name="uq_defense_groups_plan_slot_room"
        ),
    )
    op.create_index(op.f("ix_defense_groups_plan_id"), "defense_groups", ["plan_id"], unique=False)
    op.create_table(
        "panel_assignments",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("is_chair", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["defense_groups.id"],
            name=op.f("fk_panel_assignments_group_id_defense_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["schedule_plans.id"],
            name=op.f("fk_panel_assignments_plan_id_schedule_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_panel_assignments_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_panel_assignments")),
        sa.UniqueConstraint("group_id", "teacher_id", name="uq_panel_assignments_group_teacher"),
    )
    op.create_index(
        op.f("ix_panel_assignments_group_id"), "panel_assignments", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_panel_assignments_plan_id"), "panel_assignments", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_panel_assignments_teacher_id"), "panel_assignments", ["teacher_id"], unique=False
    )
    op.create_table(
        "student_assignments",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["defense_groups.id"],
            name=op.f("fk_student_assignments_group_id_defense_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["schedule_plans.id"],
            name=op.f("fk_student_assignments_plan_id_schedule_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_assignments_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_assignments")),
        sa.UniqueConstraint("plan_id", "student_id", name="uq_student_assignments_plan_student"),
    )
    op.create_index(
        op.f("ix_student_assignments_group_id"), "student_assignments", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_assignments_plan_id"), "student_assignments", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_assignments_student_id"),
        "student_assignments",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "teacher_confirmations",
        sa.Column("panel_assignment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", name="confirmation_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_assignment_id"],
            ["panel_assignments.id"],
            name=op.f("fk_teacher_confirmations_panel_assignment_id_panel_assignments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_confirmations")),
        sa.UniqueConstraint(
            "panel_assignment_id", name=op.f("uq_teacher_confirmations_panel_assignment_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_confirmations")
    op.drop_index(op.f("ix_student_assignments_student_id"), table_name="student_assignments")
    op.drop_index(op.f("ix_student_assignments_plan_id"), table_name="student_assignments")
    op.drop_index(op.f("ix_student_assignments_group_id"), table_name="student_assignments")
    op.drop_table("student_assignments")
    op.drop_index(op.f("ix_panel_assignments_teacher_id"), table_name="panel_assignments")
    op.drop_index(op.f("ix_panel_assignments_plan_id"), table_name="panel_assignments")
    op.drop_index(op.f("ix_panel_assignments_group_id"), table_name="panel_assignments")
    op.drop_table("panel_assignments")
    op.drop_index(op.f("ix_defense_groups_plan_id"), table_name="defense_groups")
    op.drop_table("defense_groups")
    op.drop_index(
        op.f("ix_constraint_exceptions_constraint_code"), table_name="constraint_exceptions"
    )
    op.drop_index(op.f("ix_constraint_exceptions_activity_id"), table_name="constraint_exceptions")
    op.drop_table("constraint_exceptions")
    op.drop_table("student_directions")
    op.drop_index(op.f("ix_schedule_plans_activity_id"), table_name="schedule_plans")
    op.drop_table("schedule_plans")
    op.drop_index(op.f("ix_schedule_jobs_activity_id"), table_name="schedule_jobs")
    op.drop_table("schedule_jobs")
    op.drop_index(op.f("ix_defense_slots_activity_id"), table_name="defense_slots")
    op.drop_table("defense_slots")
    op.drop_index(op.f("ix_activity_rule_sets_activity_id"), table_name="activity_rule_sets")
    op.drop_table("activity_rule_sets")
    op.drop_table("activity_rooms")
    op.drop_table("teacher_directions")
    op.drop_index(op.f("ix_students_student_number"), table_name="students")
    op.drop_index(op.f("ix_students_major_id"), table_name="students")
    op.drop_index(op.f("ix_students_department_id"), table_name="students")
    op.drop_index(op.f("ix_students_advisor_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_room_availabilities_room_id"), table_name="room_availabilities")
    op.drop_table("room_availabilities")
    op.drop_index(op.f("ix_defense_activities_department_id"), table_name="defense_activities")
    op.drop_table("defense_activities")
    op.drop_index(op.f("ix_course_occupancies_starts_at"), table_name="course_occupancies")
    op.drop_index(op.f("ix_course_occupancies_person_id"), table_name="course_occupancies")
    op.drop_index(op.f("ix_course_occupancies_department_id"), table_name="course_occupancies")
    op.drop_table("course_occupancies")
    op.drop_index(op.f("ix_teachers_employee_number"), table_name="teachers")
    op.drop_index(op.f("ix_teachers_department_id"), table_name="teachers")
    op.drop_table("teachers")
    op.drop_index(op.f("ix_rooms_department_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_role_assignments_user_id"), table_name="role_assignments")
    op.drop_index(op.f("ix_role_assignments_department_id"), table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_majors_department_id"), table_name="majors")
    op.drop_table("majors")
    op.drop_index(op.f("ix_leave_records_starts_at"), table_name="leave_records")
    op.drop_index(op.f("ix_leave_records_person_id"), table_name="leave_records")
    op.drop_index(op.f("ix_leave_records_department_id"), table_name="leave_records")
    op.drop_table("leave_records")
    op.drop_index(op.f("ix_import_batches_department_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_directions_department_id"), table_name="directions")
    op.drop_table("directions")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_object_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_object_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_academic_terms_department_id"), table_name="academic_terms")
    op.drop_table("academic_terms")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
